### ISSUE TITLE
plugin errors

### ISSUE THREAD

**Issue by gab696** [piramja/inventree-niimbot-plugin#4]
Hi,
I can't correctly install and use your plugin on my docker setup
Inventree v.0.17.1
I got theses errors,
Thanks !

Message : cannot import name 'ImageDraw' from 'PIL' (/root/.local/lib/python3.11/site-packages/PIL/__init__.py)

Traceback (most recent call last):

File "/home/inventree/src/backend/InvenTree/report/api.py", line 271, in print

plugin.print_labels(

File "/home/inventree/src/backend/InvenTree/plugin/base/label/mixins.py", line 156, in print_labels

pdf_data = pdf_file.get_document().write_pdf()

^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django_weasyprint/views.py", line 81, in get_document

string=super().rendered_content,

^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content

return template.render(context, self._request)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render

return self.template.render(context)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 175, in render

return self._render(context)

^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render

return self.nodelist.render(context)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render

return SafeString("".join([node.render_annotated(context) for node in self]))

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>

return SafeString("".join([node.render_annotated(context) for node in self]))

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated

return self.render(context)

^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render

return compiled_parent._render(context)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render

return self.nodelist.render(context)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render

return SafeString("".join([node.render_annotated(context) for node in self]))

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>

return SafeString("".join([node.render_annotated(context) for node in self]))

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated

return self.render(context)

^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render

result = block.nodelist.render(context)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render

return SafeString("".join([node.render_annotated(context) for node in self]))

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>

return SafeString("".join([node.render_annotated(context) for node in self]))

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated

return self.render(context)

^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/library.py", line 237, in render

output = self.func(*resolved_args, **resolved_kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/src/backend/InvenTree/report/templatetags/barcode.py", line 85, in qrcode

qri = qr.make_image(fill_color=fill_color, back_color=back_color)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/qrcode/main.py", line 363, in make_image

from qrcode.image.pil import Image, PilImage

File "/root/.local/lib/python3.11/site-packages/qrcode/image/pil.py", line 2, in <module>

from PIL import Image, ImageDraw

ImportError: cannot import name 'ImageDraw' from 'PIL' (/root/.local/lib/python3.11/site-packages/PIL/__init__.py)

**Comment by gab696** [comment]
Now I can't print QR codes or reports without getting this error:
I've tried to disable all additional plugins and restarting the server...

Error object (23)
[Historique](http://192.168.2.15/admin/error_report/error/23/history/)

Type :
TypeError
Path :
plugins.inventreelabel.print_labels
Info :
'NoneType' object is not callable
When :
30 décembre 2024 11:47
Data :
Traceback (most recent call last):

File "/home/inventree/src/backend/InvenTree/report/api.py", line 271, in print
plugin.print_labels(

File "/home/inventree/src/backend/InvenTree/plugin/base/label/mixins.py", line 156, in print_labels
pdf_data = pdf_file.get_document().write_pdf()
^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django_weasyprint/views.py", line 81, in get_document
string=super().rendered_content,
^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
return template.render(context, self._request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
return self.template.render(context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 175, in render
return self._render(context)
^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
return self.nodelist.render(context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
return SafeString("".join([node.render_annotated(context) for node in self]))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
return SafeString("".join([node.render_annotated(context) for node in self]))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
return self.render(context)
^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
return compiled_parent._render(context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
return self.nodelist.render(context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
return SafeString("".join([node.render_annotated(context) for node in self]))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
return SafeString("".join([node.render_annotated(context) for node in self]))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
return self.render(context)
^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
result = block.nodelist.render(context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
return SafeString("".join([node.render_annotated(context) for node in self]))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
return SafeString("".join([node.render_annotated(context) for node in self]))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
return self.render(context)
^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/template/library.py", line 237, in render
output = self.func(*resolved_args, **resolved_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/src/backend/InvenTree/report/templatetags/barcode.py", line 102, in barcode
barcode_image = constructor(data, writer=writer())
^^^^^^^^

TypeError: 'NoneType' object is not callable

**Comment by piramja** [comment]
I found the whole plugin system to be broken in the docker image. I was not able to repair it in a satisfying way, so i switched to the bare metal installation. This fixed all the problems with the plugin system as well as some other issues.

Besides that i was never actually able to verify if the necessary bluetooth connectivity is even possible from within a docker image.

**Comment by gab696** [comment]
Bare install is a pain... Packages are not compatible (apt key is outdated) I wasted a day trying to resolve issues. I thought Inventree was more robust but I was wrong with that
Now I can no longer print reports or labels without errors. 
I think the PIP or Pillow package is missing or the installed version is not compatible.
Could you tell me the version to install?

**Comment by piramja** [comment]
Well quite some time passed since i did the install, but i think it was pretty straight forward, with good instructions in the manual. Just clone the current release from GitHub and follow the manual.

I found InvenTree to be pretty robust if set up correctly. I use it in production for about a year now without any problems. Only the docker image seems to be messed up somehow... it was all about include paths not working out as far as i remember...

But the bare metal install worked great and for me it was absolutely worth it. I love working with InvenTree, it's really a breeze.
